// tables.js
// Data is a simple “range table” format: [{min, max, text}, ...]
// Router picks a category; then we roll on that category table.

window.BG_TABLES = {
  router: [
    { min: 1, max: 8, text: "Agriculture, Animals & Forestry" },
    { min: 9, max: 16, text: "Architecture & Construction" },
    { min: 17, max: 23, text: "The Arts" },
    { min: 24, max: 30, text: "Business & Trade" },
    { min: 31, max: 37, text: "Communications" },
    { min: 38, max: 44, text: "Craftsmanship" },
    { min: 45, max: 51, text: "Crime" },
    { min: 52, max: 58, text: "Government & Law" },
    { min: 59, max: 65, text: "Hospitality and Common Labor" },
    { min: 66, max: 72, text: "Military & Security" },
    { min: 73, max: 79, text: "Religion" },
    { min: 80, max: 86, text: "Sciences & Education" },
    { min: 87, max: 93, text: "Transportation" },
    { min: 94, max: 100, text: "Unemployed, Self-Employed, or Outcast" }
  ],

  categories: {
    "Agriculture, Animals & Forestry": [
      { min: 1, max: 3, text: "Animal/Monster Handler – responsible for the safe keeping, dietary care, and exercise of animals or monsters." },
      { min: 4, max: 6, text: "Arborist – maintains and cares for trees, often by surgically removing dying limbs." },
      { min: 7, max: 9, text: "Baler – bales hay, or in the mills, wool and cotton goods." },
      { min: 10, max: 11, text: "Beekeeper – owns and breeds bees, especially for their honey." },
      { min: 12, max: 14, text: "Breeder – breeds livestock, animals, or monsters." },
      { min: 15, max: 17, text: "Cowherd – supervises grazing cattle." },
      { min: 18, max: 20, text: "Dairyboy/Dairymaid – milks cows and makes cheese and butter." },
      { min: 21, max: 23, text: "Falconer – keeps, trains, and hunts with falcons, hawks, or other birds of prey." },
      { min: 24, max: 26, text: "Farmer – operates a farm or cultivates land." },
      { min: 27, max: 29, text: "Fisher – catches fish." },
      { min: 30, max: 31, text: "Florist – grows and arranges plants and cut flowers." },
      { min: 32, max: 34, text: "Forager – searches for food in the wild." },
      { min: 35, max: 37, text: "Forester – supervises the wellbeing of a forest." },
      { min: 38, max: 40, text: "Fowler – catches or ensnares birds." },
      { min: 41, max: 43, text: "Gamekeeper – breeds and protects game, typically for a large estate." },
      { min: 44, max: 46, text: "Groom – cleans and brushes the coats horses, dogs, or other animals." },
      { min: 47, max: 49, text: "Herder – supervises a herd of livestock or makes a living from keeping livestock, especially in open country." },
      { min: 50, max: 51, text: "Horse Trainer – tends to horses and teaches them different disciplines." },
      { min: 52, max: 54, text: "Hunter – hunts game or other wild animals." },
      { min: 55, max: 57, text: "Lumberjack – fells trees, cuts them into logs, and transports them to a sawmill." },
      { min: 58, max: 60, text: "Master-of-Horses – supervises and commands all horses under a jurisdiction." },
      { min: 61, max: 63, text: "Master-of-Hounds – maintains a pack of hounds and their associated staff, equipment, and hunting arrangements." },
      { min: 64, max: 66, text: "Miller – owns or works in a grain mill." },
      { min: 67, max: 69, text: "Miner – works underground in mines in order to obtain minerals such as coal, diamonds, or gold." },
      { min: 70, max: 71, text: "Pathfinder – scouts ahead and discovers a path or way for others." },
      { min: 72, max: 74, text: "Plumer – hunts birds for their plumes." },
      { min: 75, max: 77, text: "Prospector – searches for mineral deposits, especially by drilling and excavation." },
      { min: 78, max: 80, text: "Ranger – wanders or ranges over a particular area or domain." },
      { min: 81, max: 83, text: "Renderer – converts waste animal tissue into usable materials." },
      { min: 84, max: 86, text: "Shepherd – herds, tends, and guards sheep." },
      { min: 87, max: 89, text: "Stablehand – works in a stable." },
      { min: 90, max: 91, text: "Thresher – separates grain from the plants by beating." },
      { min: 92, max: 94, text: "Trapper – traps wild animals, especially for their fur." },
      { min: 95, max: 97, text: "Vintner – engages in winemaking, especially with monitoring and harvesting the grapes." },
      { min: 98, max: 100, text: "Zookeeper – maintains and cares for animals or monsters in a zoo." }
    ],

    "Architecture & Construction": [
      { min: 1, max: 9, text: "Architect – designs buildings or landscapes and in many cases supervises their construction." },
      { min: 10, max: 18, text: "Brickmaker – crafts bricks from clay, stone, or other materials." },
      { min: 19, max: 27, text: "Brickmason – builds with mineral products such as stones, bricks, tiles, etc. usually with the use of mortar." },
      { min: 28, max: 36, text: "Carpenter – makes and repairs wooden objects and structures." },
      { min: 37, max: 45, text: "Construction Worker – a laborer in the physical construction of a built environment and its infrastructure." },
      { min: 46, max: 55, text: "General Contractor – supervises a construction site, manages its vendors and trades, and associated communication." },
      { min: 56, max: 64, text: "Glazier – fits glass into windows and doors." },
      { min: 65, max: 73, text: "Plasterer – applies plaster to walls, ceilings, or other surfaces." },
      { min: 74, max: 82, text: "Roadlayer/Streetlayer – paves roads or streets." },
      { min: 83, max: 91, text: "Roofer/Thatcher – builds and repairs roofs." },
      { min: 92, max: 100, text: "Stonemason – cuts and prepares stone for use in construction." }
    ],

    "The Arts": [
      { min: 1, max: 2, text: "Acrobat – performs spectacular gymnastic feats." },
      { min: 3, max: 5, text: "Actor – impersonates characters, typically on stage in a theatrical production." },
      { min: 6, max: 7, text: "Aerialist/Trapezist – performs acrobatics high above the ground on a tightrope or trapeze." },
      { min: 8, max: 10, text: "Arranger – adapts a musical composition for performance." },
      { min: 11, max: 12, text: "Athlete – proficient in sports and other forms of physical exercise." },
      { min: 13, max: 15, text: "Busker/Street Musician – performs in a public place, often for money." },
      { min: 16, max: 17, text: "Celebrity – a famous person." },
      { min: 18, max: 20, text: "Chef – a professional cook trained in the culinary arts." },
      { min: 21, max: 22, text: "Choirmaster – trains a choir and orchestrates their singing when they perform." },
      { min: 23, max: 24, text: "Clown – comic entertainer who wears a traditional costume and exaggerated makeup." },
      { min: 25, max: 27, text: "Comedian – entertainer whose act is designed to make an audience laugh." },
      { min: 28, max: 29, text: "Conductor – directs the performance of an orchestra." },
      { min: 30, max: 32, text: "Contortionist – twists and bends their body into strange and unnatural positions." },
      { min: 33, max: 34, text: "Curator – keeper and custodian of a museum or other collections of precious items." },
      { min: 35, max: 37, text: "Costumer – makes theatrical costumes." },
      { min: 38, max: 39, text: "Dancer – moves their body rhythmically with or without musical accompaniment." },
      { min: 40, max: 41, text: "Equilibrist – performs balancing feats." },
      { min: 42, max: 44, text: "Fashion Designer – applies design, aesthetics and natural beauty to garments and their accessories." },
      { min: 45, max: 46, text: "Gladiator – fights against other people, wild animals, or monsters in an arena." },
      { min: 47, max: 49, text: "Glasspainter – produces colorful designs on or in glass." },
      { min: 50, max: 51, text: "Jester – professional joker or “fool” at court, typically wearing a cap with bells on it and carrying a mock scepter." },
      { min: 52, max: 54, text: "Juggler – keeps several objects in motion in the air at the same time by alternately tossing and catching them." },
      { min: 55, max: 56, text: "Illuminator – paints and calligraphs to adorn or enlighten scrolls and manuscripts." },
      { min: 57, max: 59, text: "Limner – paints portraits or miniatures." },
      { min: 60, max: 61, text: "Makeup Artist – applies cosmetics to models, actors, nobles, etc." },
      { min: 62, max: 63, text: "Minstrel – recites lyric or heroic poetry for nobility." },
      { min: 64, max: 66, text: "Model – poses as a subject for an artist, fashion designer, or sculptor." },
      { min: 67, max: 68, text: "Musician – plays a musical instrument." },
      { min: 69, max: 71, text: "Painter – paints pictures." },
      { min: 72, max: 73, text: "Playwright – writes plays or musicals." },
      { min: 74, max: 76, text: "Poet – writes ballads, epics, sonnets, or other forms of poetry." },
      { min: 77, max: 78, text: "Ringmaster/Ringmistress – master of ceremony who introduces the circus acts to the audience." },
      { min: 79, max: 80, text: "Ropewalker – walks along a tightrope to entertain others." },
      { min: 81, max: 83, text: "Sculptor – crafts art by carving or casting blocks of marble, stones, or other hardened minerals." },
      { min: 84, max: 85, text: "Singer/Soprano – sings with or without instrumental accompaniment." },
      { min: 86, max: 88, text: "Stage Magician – deceives their audience with seemingly impossible feats while using only natural means." },
      { min: 89, max: 90, text: "Stuntman/Stuntwoman – performs dangerous stunts for their audience." },
      { min: 91, max: 93, text: "Tattooist – illustrates the skin with indelible patterns, pictures, legends, etc." },
      { min: 94, max: 95, text: "Theater Director – orchestrates the mounting of a theatre production." },
      { min: 96, max: 98, text: "Wrestler – performs in matches involving grappling and grappling-type techniques." },
      { min: 99, max: 100, text: "Writer – commits his or her thoughts, ideas, etc., into written language." }
    ],

    "Business & Trade": [
      { min: 1, max: 4, text: "Accountant – keeps and inspects financial accounts." },
      { min: 5, max: 7, text: "Actuary – compiles and analyzes statistics and uses them to calculate risk." },
      { min: 8, max: 11, text: "Animal Collector/Monster Collector – collects and deals in rare and exotic animals and monsters." },
      { min: 12, max: 14, text: "Business Owner – owns a business entity in an attempt to profit from its successful operations." },
      { min: 15, max: 18, text: "Debt Collector – recovers money owed on delinquent accounts." },
      { min: 19, max: 21, text: "Draper – an alcohol merchant." },
      { min: 22, max: 25, text: "Appraiser – assesses the monetary value of something." },
      { min: 26, max: 29, text: "Auctioneer – conducts auctions by accepting bids and declaring goods sold." },
      { min: 30, max: 32, text: "Banker – an officer or owner of a bank or group of banks." },
      { min: 33, max: 36, text: "Bagniokeeper – owner of a bath house or brothel." },
      { min: 37, max: 39, text: "Bookkeeper – keeps records of financial affairs." },
      { min: 40, max: 43, text: "Chandler – deals in provisions and supplies." },
      { min: 44, max: 46, text: "Collector – collects things of a specified type, professionally or as a hobby." },
      { min: 47, max: 50, text: "Entrepreneur – operates a business or businesses, taking on greater than normal financial risks in order to do so." },
      { min: 51, max: 54, text: "Grocer – a food merchant." },
      { min: 55, max: 57, text: "Guild Master – leads an economically independent producer (a “guild,” an association of craftsmen or merchants)." },
      { min: 58, max: 61, text: "Innkeeper – owns and runs an inn." },
      { min: 62, max: 64, text: "Land Surveyor – establishes maps and boundaries for ownership or other purposes as required." },
      { min: 65, max: 68, text: "Merchant – sells and trades goods." },
      { min: 69, max: 71, text: "Moneychanger – exchanges one currency for another." },
      { min: 72, max: 75, text: "Moneylender – lends money to others who pay interest." },
      { min: 76, max: 79, text: "Peddler – travels from place to place selling assorted items." },
      { min: 80, max: 82, text: "Pimp/Madame – controls prostitutes and arranges clients for them, taking part of their earnings in return." },
      { min: 83, max: 86, text: "Plantation Owner – an owner of an estate on which crops are cultivated by resident labor, typically slave labor." },
      { min: 87, max: 89, text: "Speculator – invests in stocks, property, or other ventures in the hope of making a profit." },
      { min: 90, max: 93, text: "Thriftdealer – deals in secondhand items." },
      { min: 94, max: 96, text: "Tradesman – deals exclusively in bartering." },
      { min: 97, max: 100, text: "Vendor – deals items in the street." }
    ],

    "Communications": [
      { min: 1, max: 13, text: "Billboardposter – a person who puts up notices, signs and advertisements." },
      { min: 14, max: 25, text: "Courier – transports packages and documents." },
      { min: 26, max: 38, text: "Herald – a messenger who carries important news." },
      { min: 39, max: 50, text: "Interpreter – interprets language and its meaning, especially within ancient manuscripts." },
      { min: 51, max: 63, text: "Linguist – studies the essence of communication, including the units, nature, structure, and modification of language." },
      { min: 64, max: 75, text: "Messenger – carries messages between recipients." },
      { min: 76, max: 88, text: "Town Crier – makes public announcements in the streets or marketplace." },
      { min: 89, max: 100, text: "Translator – translates between languages." }
    ],

    "Craftsmanship": [
      { min: 1, max: 2, text: "Accoutrementer/Coinsmith – makes currency for the government." },
      { min: 3, max: 4, text: "Armorer – specializes in making and repairing armor." },
      { min: 5, max: 6, text: "Blacksmith – forges and repairs things in metal, including weapons, armor, utensils, etc." },
      { min: 7, max: 8, text: "Bladesmith – specializes in making and repairing bladed weapons, especially swords and daggers." },
      { min: 9, max: 10, text: "Bookbinder – binds books and wraps scrolls." },
      { min: 11, max: 12, text: "Bottler – bottles drinks and other liquids." },
      { min: 13, max: 14, text: "Bowyer – makes bows and crossbows." },
      { min: 15, max: 16, text: "Brewer – brews ale." },
      { min: 17, max: 18, text: "Broom Maker – makes brooms and brushes." },
      { min: 19, max: 20, text: "Candlemaker – makes candles and wax from honey and tallow." },
      { min: 21, max: 22, text: "Cartwright – makes and repairs carts and wagons." },
      { min: 23, max: 24, text: "Cobbler – makes and repairs footwear." },
      { min: 25, max: 26, text: "Cooper/Hooper – makes and repairs casks and barrels." },
      { min: 27, max: 28, text: "Cutler – makes cutlery." },
      { min: 29, max: 30, text: "Dyer – dyes cloth and other materials." },
      { min: 31, max: 32, text: "Embroiderer – ornaments with needlework." },
      { min: 33, max: 34, text: "Engraver – incises a design onto a hard surface by cutting grooves into it." },
      { min: 35, max: 36, text: "Farrier – trims and shoes horses' hooves." },
      { min: 37, max: 38, text: "Fletcher – makes and repairs arrows." },
      { min: 39, max: 40, text: "Furniture Artisan – makes and repairs furniture." },
      { min: 41, max: 42, text: "Furrier – prepares furs for adornment." },
      { min: 43, max: 44, text: "Glassworker – blows glass planes and items." },
      { min: 45, max: 46, text: "Glovemaker – makes and repairs gloves." },
      { min: 47, max: 48, text: "Goldsmith/Silversmith – a smith who specializes in precious metals." },
      { min: 49, max: 50, text: "Hatter/Milliner – makes and repairs headwear." },
      { min: 51, max: 52, text: "Instrument Maker – makes and repairs musical instruments." },
      { min: 53, max: 54, text: "Lapidary – turns stone/minerals/gemstones into decorative items such as cabochons, engraved gems, etc." },
      { min: 55, max: 56, text: "Leatherworker – makes items from leather such as pouches, scabbards, straps, etc." },
      { min: 57, max: 58, text: "Jeweler – designs, makes, and repairs necklaces, bracelets, watches, etc., often containing jewels." },
      { min: 59, max: 60, text: "Locksmith – makes and repairs locks." },
      { min: 61, max: 62, text: "Luthier – makes and repairs stringed instruments." },
      { min: 63, max: 64, text: "Mercer – weaves textile fabrics, especially silks, velvets, and other fine materials." },
      { min: 65, max: 66, text: "Optician – makes and repairs eyeglasses." },
      { min: 67, max: 68, text: "Potter – makes pots, bowls, plates, etc., out of clay." },
      { min: 69, max: 70, text: "Printer – a person who applies pressure to an inked surface resting upon a print medium (such as paper or cloth)." },
      { min: 71, max: 72, text: "Restorer – repairs or renovates a work of art so as to return it to its original condition." },
      { min: 73, max: 74, text: "Ropemaker – braids rope." },
      { min: 75, max: 76, text: "Rugmaker – makes and repairs rugs by braiding, hooking, weaving, etc." },
      { min: 77, max: 78, text: "Saddler – makes and repairs saddlery." },
      { min: 79, max: 80, text: "Seamstress/Tailor – makes, alters, repairs, as well as occasionally designing garments." },
      { min: 81, max: 82, text: "Soaper – makes soap from accumulated mutton fat, wood ash, and natural soda." },
      { min: 83, max: 84, text: "Tanner – treats the skins and hides of animals to produce leather." },
      { min: 85, max: 86, text: "Taxidermist – prepares, stuffs, and mounts the skins of animals." },
      { min: 87, max: 88, text: "Tinker – travels from place to place mending utensils." },
      { min: 89, max: 90, text: "Toymaker – makes and repairs toys." },
      { min: 91, max: 92, text: "Watchmaker – makes and repairs watches and clocks." },
      { min: 93, max: 94, text: "Weaponsmith – specializes in making and repairing weapons." },
      { min: 95, max: 96, text: "Weaver – makes fabric by weaving fiber together." },
      { min: 97, max: 98, text: "Wheelwright – makes and repairs wooden wheels." },
      { min: 99, max: 100, text: "Whittler/Woodcarver – fashions wood into various shapes." }
    ],

    "Crime": [
      { min: 1, max: 6, text: "Assassin – murders through stealth for reasons pertaining to money, politics, or religion." },
      { min: 7, max: 12, text: "Bandit – a robber or outlaw belonging to a gang and typically operating in an isolated or lawless area." },
      { min: 13, max: 18, text: "Burglar – illegally enters buildings and steals things." },
      { min: 19, max: 24, text: "Charlatan/Conman – person who exploits the others for their own sake by manipulation of their confidence." },
      { min: 25, max: 29, text: "Cockfighter/Gamefighter – engages in matches in which creatures are pitted against one another, typically to death." },
      { min: 30, max: 35, text: "Drug Dealer – dealer of illegal substances." },
      { min: 36, max: 41, text: "Extortioner – extorts money from someone by threatening to expose embarrassing information about them." },
      { min: 42, max: 47, text: "Fence – deals in stolen goods." },
      { min: 48, max: 53, text: "Forger – produces fraudulent copies or imitations." },
      { min: 54, max: 59, text: "Fugitive – a person who has escaped from a place or is in hiding, especially to avoid arrest or persecution." },
      { min: 60, max: 65, text: "Highwayman – robs travelers on a road." },
      { min: 66, max: 71, text: "Kidnapper – abducts people and holds them captive, typically to obtain a ransom." },
      { min: 72, max: 76, text: "Loan Shark – charges extremely high rates of interest for moneylending, typically under illegal conditions." },
      { min: 77, max: 82, text: "Pirate – attacks and robs ships at sea." },
      { min: 83, max: 88, text: "Poacher – hunts illegal game." },
      { min: 89, max: 94, text: "Raider/Marauder – makes sudden, unprompted attacks against defenseless or near-defenseless settlements." },
      { min: 95, max: 100, text: "Smuggler – imports/exports goods secretly, in violation of the law, especially without payment of legal duty." }
    ],

    "Government & Law": [
      { min: 1, max: 5, text: "Affeeror – determines the values of fines and amercements." },
      { min: 6, max: 10, text: "Agister – affords pasture to the livestock of others for a price." },
      { min: 11, max: 15, text: "Alderman – a civic dignitary in the local council ranked below the mayor." },
      { min: 16, max: 20, text: "Alienist – assesses the competence of a defendant in a court of law." },
      { min: 21, max: 25, text: "Assay Master – oversees the testing of currency." },
      { min: 26, max: 30, text: "Chief – leads or rules a people or clan." },
      { min: 31, max: 35, text: "Conservationist – advocates for the protection and preservation of the environment and wildlife." },
      { min: 36, max: 40, text: "Judge – decides cases in a court of law." },
      { min: 41, max: 45, text: "Lady-in-Waiting – attends a queen, princess, or other high-ranking feminine nobleperson." },
      { min: 46, max: 50, text: "Lawyer/Advocate – practices or studies law, typically an attorney or a counselor." },
      { min: 51, max: 55, text: "Minister – assists with the administration of business." },
      { min: 56, max: 60, text: "Noble/Aristocrat – a person belonging to a class with high social or political status." },
      { min: 61, max: 65, text: "Notary – performs certain legal formalities, draw up or certify contracts, deeds, and other documents for use." },
      { min: 66, max: 70, text: "Orator/Spokesman – makes statements on behalf of a group or individual nobleperson." },
      { min: 71, max: 75, text: "Page – a young attendant to a person of noble rank." },
      { min: 76, max: 80, text: "Sheriff – the chief executive officer in a county, having various administrative and judicial functions." },
      { min: 81, max: 85, text: "Steward – supervises both the estate and household of his lord or lady while they are away." },
      { min: 86, max: 90, text: "Squire – acts as an attendant to a knight before attempting to become a knight themselves." },
      { min: 91, max: 95, text: "Tax Collector – collects unpaid taxes from people, guilds, or businesses." },
      { min: 96, max: 100, text: "Ward – a member of a noble house who has been taken in by another noble family to be raised for a time." }
    ],

    "Hospitality and Common Labor": [
      { min: 1, max: 2, text: "Acater – provides and prepares foodstuffs or delicacies for events such as festivals." },
      { min: 3, max: 5, text: "Tunner – fills casks in a brewery or winery." },
      { min: 6, max: 7, text: "Baker – bakes bread and cakes." },
      { min: 8, max: 9, text: "Barber – cuts hair and shaves or trims beards." },
      { min: 10, max: 12, text: "Barkeep – works and serves drinks in a bar." },
      { min: 13, max: 14, text: "Barmaid/Barboy – serves drinks and food in a bar as well as engaging with customers." },
      { min: 15, max: 16, text: "Butcher – cuts up and sells meat." },
      { min: 17, max: 19, text: "Butler – the chief servant of a household." },
      { min: 20, max: 21, text: "Caregiver – looks after a sick, elderly, or disabled person." },
      { min: 22, max: 23, text: "Charcoal Maker – manufactures charcoal by carbonizing wood in a kiln." },
      { min: 24, max: 26, text: "Chatelaine/Majordomo – a person in charge of a large household." },
      { min: 27, max: 28, text: "Chimney Sweeper – a small person, typically a child, who ascends chimneys to clean them." },
      { min: 29, max: 30, text: "Clerk – undertakes routine administrative duties in a business or bank." },
      { min: 31, max: 33, text: "Cook – prepares food for eating." },
      { min: 34, max: 35, text: "Copyist – makes copies of handwritten documents or music." },
      { min: 36, max: 37, text: "Croupier – runs a gaming table by gathering in and paying out money or tokens." },
      { min: 38, max: 40, text: "Exterminator – exterminates unwanted rodents and insects." },
      { min: 41, max: 42, text: "Food & Drink Taster – ingests food that was prepared for someone else to confirm it is safe to eat." },
      { min: 43, max: 44, text: "Gardener/Landscaper – tends and cultivates a garden." },
      { min: 45, max: 47, text: "Gongfarmer – digs out and removes excrement from privies and cesspits." },
      { min: 48, max: 49, text: "Gravedigger – digs graves for the purposes of a funeral ceremony." },
      { min: 50, max: 51, text: "Groundskeeper – maintains an athletic field, a park, or the grounds of a graveyard or other institution." },
      { min: 52, max: 53, text: "Kitchen Drudge – performs menial work in a kitchen." },
      { min: 54, max: 56, text: "Knacker – disposes of dead or unwanted animals." },
      { min: 57, max: 58, text: "Lamplighter – lights street or road lights at dusk." },
      { min: 59, max: 60, text: "Laundry Worker – a laborer who takes part in the washing, drying, and ironing of clothes and other fabric items." },
      { min: 61, max: 63, text: "Lector – reads to others while they work for entertainment." },
      { min: 64, max: 65, text: "Longshoreman – loads and unloads ships in a port." },
      { min: 66, max: 67, text: "Maid – a domestic servant of a household." },
      { min: 68, max: 70, text: "Nanny/Nursemaid – a servant employed to look after a young child or children." },
      { min: 71, max: 72, text: "Operator – a laborer who operates equipment, typically in construction." },
      { min: 73, max: 74, text: "Pastry Chef – makes desserts, especially cakes and pastries." },
      { min: 75, max: 77, text: "Plumber – installs and repairs the fittings of water supply and sanitation." },
      { min: 78, max: 79, text: "Porter – carries luggage and other loads." },
      { min: 80, max: 81, text: "Prostitute – engages in sexual activity for payment." },
      { min: 82, max: 84, text: "Quarryman/Quarrywoman – quarries stone." },
      { min: 85, max: 86, text: "Servant – performs duties for others, especially a person employed in a house or as a personal attendant." },
      { min: 87, max: 88, text: "Stagehand – moves scenery or props before or during the performance of a theatrical production." },
      { min: 89, max: 91, text: "Street Cleaner – cleans streets and alleyways after dark." },
      { min: 92, max: 93, text: "Talent Scout – searches for talented individuals who can be employed or promoted." },
      { min: 94, max: 95, text: "Trainer – trains someone in a particular skill, usually physical, for money." },
      { min: 96, max: 98, text: "Water Bearer – brings water from rivers, wells, and lakes back to their settlement." },
      { min: 99, max: 100, text: "Wet Nurse – a woman employed to suckle another woman's child." }
    ],

    "Military & Security": [
      { min: 1, max: 3, text: "Bailiff – looks after prisoners." },
      { min: 4, max: 6, text: "Bodyguard – escorts and protects another person, especially a dignitary." },
      { min: 7, max: 9, text: "Bouncer – prevents troublemakers from entering or to eject them from the premises of an establishment." },
      { min: 10, max: 11, text: "Captain – an army officer of high rank in charge of commanding squadrons of soldiers." },
      { min: 12, max: 14, text: "Cavalryman/Cavalier – a skilled horseback rider." },
      { min: 15, max: 17, text: "City Watch – an officer of law enforcement who resides in larger towns or cities." },
      { min: 18, max: 20, text: "Commissar – teaches principles and policies to military units." },
      { min: 21, max: 23, text: "Constable – an officer with limited policing authority, typically in a small town." },
      { min: 24, max: 26, text: "Detective/Investigator – investigates and solves crimes." },
      { min: 27, max: 29, text: "Drummer/Fifer – a non-combatant foot soldier who sounds signals for changes in formation in combat." },
      { min: 30, max: 31, text: "Duelist – skilled in one-on-one combat." },
      { min: 32, max: 34, text: "Executioner – carries out a sentence of death on a legally condemned person." },
      { min: 35, max: 37, text: "Firefighter – extinguishes fires." },
      { min: 38, max: 40, text: "Guard/Sentinel – a person who keeps watch, formally assigned to protect a person or place." },
      { min: 41, max: 43, text: "Inspection Officer – responsible to ensure military units meet appropriate standards of training and efficiency." },
      { min: 44, max: 46, text: "Intelligence Officer – collects, compiles and organizes information about the enemy." },
      { min: 47, max: 49, text: "Jailer – supervises a jail and the prisoners in it." },
      { min: 50, max: 51, text: "Marksman/Archer – in long-range weapons, such as the bow, crossbow, sling, etc. to inflict damage from afar." },
      { min: 52, max: 54, text: "Medic – a medical practitioner equipped for the battlefield." },
      { min: 55, max: 57, text: "Mercenary – a soldier without allegiance who works for money, typically a member of a company or guild." },
      { min: 58, max: 60, text: "Privateer – engages in maritime warfare under a commission of war." },
      { min: 61, max: 63, text: "Quartermaster – responsible for providing quarters, rations, clothing, and other supplies." },
      { min: 64, max: 66, text: "Royal Guard – responsible for the protection of a royal person." },
      { min: 67, max: 69, text: "Runner – carries information between lines in wartime." },
      { min: 70, max: 71, text: "Sapper – a soldier responsible for tasks such as building, repairing and destroying roads and bridges, etc." },
      { min: 72, max: 74, text: "Sergeant-at-Arms – charged with keeping order during meetings and, if necessary, participates in battle." },
      { min: 75, max: 77, text: "Scout – sent ahead of a main force so as to gather information about the enemy's position, strength, or movements." },
      { min: 78, max: 80, text: "Siege Artillerist – works the artillery machines of an army." },
      { min: 81, max: 83, text: "Slave Driver – oversees and urges on slaves at work." },
      { min: 84, max: 86, text: "Soldier/Man-at-Arms – serves in an army." },
      { min: 87, max: 89, text: "Spy – secretly collects and reports information on the activities, movements, and plans of an enemy or competitor." },
      { min: 90, max: 91, text: "Tactician – uses a carefully planned military strategy to achieve a specific end." },
      { min: 92, max: 94, text: "Tollkeeper – collects tolls at a bridge, road etc. where a charge is made." },
      { min: 95, max: 97, text: "Torturer – inflicts severe pain on someone as a punishment or in order to force them to do or say something." },
      { min: 98, max: 100, text: "Warden – supervisor of a particular place or thing or for ensuring that regulations associated with it are obeyed." }
    ],

    "Religion": [
      { min: 1, max: 6, text: "Abbot/Abbess – the head of an abbey of monks." },
      { min: 7, max: 13, text: "Acolyte – assists the celebrant in a religious service or procession." },
      { min: 14, max: 19, text: "Almoner – distributes money and food to poor people." },
      { min: 20, max: 25, text: "Cantor – sings liturgical music and leads prayer in a synagogue." },
      { min: 26, max: 31, text: "Chaplain – a member of the clergy attached to a private chapel, institution, ship, branch of the armed forces, etc." },
      { min: 32, max: 38, text: "Confessor – hears confessions and gives absolution and spiritual counsel." },
      { min: 39, max: 44, text: "Cultist – a member of a cult who generally lives outside of conventional society and worships an unorthodox patron." },
      { min: 45, max: 50, text: "Deacon – an ordained minister of an order ranking below that of priest." },
      { min: 51, max: 56, text: "Diviner – seeks ultimate divination in order to further understand or meet godly substance." },
      { min: 57, max: 63, text: "Exorcist – expels or attempts to expel evil spirits from a person or place." },
      { min: 64, max: 69, text: "Inquisitor – seeks to eliminate heresy and other things contrary to the doctrine or teachings of their faith." },
      { min: 70, max: 75, text: "Missionary – goes on a religious mission to promote their faith in a foreign place." },
      { min: 76, max: 81, text: "Nun – a member of a cloistered religious community of women living vows of poverty, chastity, and obedience." },
      { min: 82, max: 88, text: "Pardoner – raises money for religious works by soliciting offerings and granting indulgences." },
      { min: 89, max: 94, text: "Prophet – regarded as an inspired teacher or proclaimer of the will of God." },
      { min: 95, max: 100, text: "Sexton – looks after a church and churchyard, sometimes acting as bell-ringer and formerly as a gravedigger." }
    ],

"Sciences & Education": [
  { min: 1, max: 3, text: "Abecedarian – teaches the illiterate." },
  { min: 4, max: 6, text: "Accoucheur/Obstetrician/Midwife – assists in childbirth and the care of women giving birth." },
  { min: 7, max: 9, text: "Apothecary – prepares and sells medicines, drugs, and potions." },
  { min: 10, max: 12, text: "Archaeologist – studies humanoid history through excavation of sites and the analysis of artifacts and other remains." },
  { min: 13, max: 14, text: "Archivist – maintains and is in charge of archives." },
  { min: 15, max: 17, text: "Assayer – determiner of the proportions of metal in ore and the amount of copper, silver, gold, or platinum in coins." },
  { min: 18, max: 20, text: "Astrologer – uses astrology to tell others about their character or to predict their future." },
  { min: 21, max: 23, text: "Astronomer – makes observations of celestial and scientific phenomena within the material plane." },
  { min: 24, max: 26, text: "Bloodletter – surgically removes some of a patient's blood for therapeutic purposes." },
  { min: 27, max: 29, text: "Botanist – an expert in or student of the scientific study of plants." },
  { min: 30, max: 31, text: "Cartographer – a scholar and illustrator of maps." },
  { min: 32, max: 34, text: "Chemist – engaged in chemical research or experiments." },
  { min: 35, max: 37, text: "Dean – the head of a college or university." },
  { min: 38, max: 40, text: "Doctor/Physician – a qualified practitioner of medicine." },
  { min: 41, max: 43, text: "Engineer – designer of a machine or structure." },
  { min: 44, max: 46, text: "Entomologist – studies or is an expert in the branch of zoology concerned with insects." },
  { min: 47, max: 49, text: "Herbalist – practices healing by the use of herbs." },
  { min: 50, max: 52, text: "Historian – an expert or student of history of a particular period, geographical region, or social phenomenon." },
  { min: 53, max: 55, text: "Horologist – a scholar of time and entropy." },
  { min: 56, max: 58, text: "Librarian – administers or assists in a library." },
  { min: 59, max: 61, text: "Mathematician – a scholar of the abstract science of number, quantity, and space." },
  { min: 62, max: 64, text: "Mortician – prepares dead bodies for burial or cremation and makes arrangements for funerals." },
  { min: 65, max: 67, text: "Nurse – cares for the sick or infirm, especially in a hospital." },
  { min: 68, max: 70, text: "Optometrist – examines the eyes for visual defects and prescribes eyeglasses." },
  { min: 71, max: 73, text: "Philosopher – a scholar of the fundamental nature of knowledge, reality, and existence." },
  { min: 74, max: 76, text: "Professor – a teacher of the highest rank in a college or university." },
  { min: 77, max: 79, text: "Scholar/Researcher – a specialist in a particular branch of study who pursues the acquisition of knowledge." },
  { min: 80, max: 82, text: "Scribe – copies out manuscripts." },
  { min: 83, max: 85, text: "Surgeon/Chirurgeon – practices surgery." },
  { min: 86, max: 88, text: "Taxonomist – groups organisms into categories." },
  { min: 89, max: 91, text: "Theologian – engages in the study of the nature of God and religious belief." },
  { min: 92, max: 94, text: "Tutor – charged with the instruction and guidance of another." },
  { min: 95, max: 97, text: "Veterinarian – treats diseased or injured animals." },
  { min: 98, max: 100, text: "Zoologist – an expert in or a student of the behavior, physiology, classification, and distribution of animals." }
],


    "Transportation": [
      { min: 1, max: 7, text: "Boatman – mans a small seacraft." },
      { min: 8, max: 13, text: "Bosun/Botswain – in charge of organizing the equipment and crew of a ship." },
      { min: 14, max: 20, text: "Cabbie/Wagoner – drives a horse-drawn wagon." },
      { min: 21, max: 27, text: "Cabin Boy/Cabin Girl – waits on the orders of a ship's officers and passengers." },
      { min: 28, max: 33, text: "Caravaneer – travels or lives in a caravan." },
      { min: 34, max: 40, text: "Charioteer – drives a chariot." },
      { min: 41, max: 47, text: "Carter – transports goods by cart." },
      { min: 48, max: 53, text: "Ferryman – operates a ferry." },
      { min: 54, max: 60, text: "First Mate – the deck officer second in command to the master of a ship." },
      { min: 61, max: 67, text: "Helmsman – steers a ship or boat." },
      { min: 68, max: 73, text: "Navigator – directs the route or course of a ship or other form of transportation using instruments and maps." },
      { min: 74, max: 80, text: "Purser – keeps the accounts of a ship, especially as the head steward on a passenger vessel." },
      { min: 81, max: 87, text: "Sailor – works as a member of the crew of a commercial or naval ship or boat." },
      { min: 88, max: 93, text: "Sea Captain – commands a ship." },
      { min: 94, max: 100, text: "Shipwright – a carpenter skilled in ship construction and repair." }
    ],

    "Unemployed, Self-Employed, or Outcast": [
      { min: 1, max: 3, text: "Adventurer – wanders the world in search of knowledge, treasure, fame, glory or a multitude of wants and desires." },
      { min: 4, max: 6, text: "Beggar/Pauper – lives by asking for money or food." },
      { min: 7, max: 10, text: "Blood Hunter/Monster Hunter – takes on jobs to hunt down and kill or capture dangerous creatures." },
      { min: 11, max: 13, text: "Bounty Hunter – pursues a criminal or fugitive for whom a reward is offered." },
      { min: 14, max: 16, text: "Crossing Sweeper – sweeps a path ahead of people crossing dirty urban streets in exchange for a gratuity." },
      { min: 17, max: 19, text: "Deserter – a member of the armed forces who has deserted." },
      { min: 20, max: 23, text: "Disgraced Noble – a person of high birth who has since lost their respect, honor, or esteem in some or all noble circles." },
      { min: 24, max: 26, text: "Drunkard – a person who is habitually drunk and considers themselves a professional in the task." },
      { min: 27, max: 29, text: "Dungeon Delver – navigates underground labyrinths in search of any treasure they may find." },
      { min: 30, max: 32, text: "Elder – a person of a greater age, especially one with a respected position in society." },
      { min: 33, max: 35, text: "Exile – lives away from their native country, either from choice or compulsion." },
      { min: 36, max: 39, text: "Explorer – explores unfamiliar areas in search of geographical or scientific information." },
      { min: 40, max: 42, text: "Ex-Criminal – convicted of a crime and has served their sentence, or who has preemptively given up their life of crime." },
      { min: 43, max: 45, text: "Folk Hero – a celebrity who is greatly admired by many people of a particular kind or in a particular place." },
      { min: 46, max: 48, text: "Gambler – bets money on sports, card games, or games of chance in the hope of a profit." },
      { min: 49, max: 52, text: "Grave Robber/Tomb Raider – steals valuables from graves and tombs." },
      { min: 53, max: 55, text: "Heretic – differs in opinion from established religious dogma." },
      { min: 56, max: 58, text: "Hermit – lives in solitude, typically as a religious or spiritual discipline." },
      { min: 59, max: 61, text: "Housewife/Househusband – cares for his or her family by managing household affairs and completing housework." },
      { min: 62, max: 65, text: "Pilgrim – journeys to some sacred place as an act of religious devotion, occasionally to settle there." },
      { min: 66, max: 68, text: "Prisoner – held in confinement as a punishment for crimes they have been convicted of." },
      { min: 69, max: 71, text: "Rag-and-Bone Man – collects unwanted household items and sells them to merchants." },
      { min: 72, max: 74, text: "Rebel/Political Dissident – rises in opposition or armed resistance against an established government or ruler." },
      { min: 75, max: 77, text: "Refugee – leaves their home in order to escape war, persecution, or natural disaster." },
      { min: 78, max: 81, text: "Runaway Slave – a slave who has left their master and traveled without authorization." },
      { min: 82, max: 84, text: "Scavenger/Mudlark/Tosher – searches for and collects discarded items." },
      { min: 85, max: 87, text: "Sin Eater – consumes a ritual meal in order to spiritually take on the sins of another." },
      { min: 88, max: 90, text: "Slave – a person who is the legal property of another and forced to obey them." },
      { min: 91, max: 94, text: "Squatter – unlawfully occupies an uninhabited building or unused land." },
      { min: 95, max: 97, text: "Traveler/Wanderer/Vagabond – wanders from place to place without a permanent home or job." },
      { min: 98, max: 100, text: "Urchin – a child who lives or spends most of their time in the streets, occasionally working as a thief or pickpocket." }
    ]
  }
};
